### PR TITLE
Fixed "Test code pattern" window not popping up

### PR DESCRIPTION
**Pull request by papstuc**
Fixes Issue #28

I have tested it with some signatures and it works fine.

### CODE REVIEW

**Comment by gir489** [comment]
This commit is unacceptable. You simply just removed the behaviour of it generating a code signature so the dialog will show. Fix the 0 selection edge case properly while still maintaining previous functionality.

**Comment by papstuc** [comment]
That's true I didn't think about it, should be fixed now

**Comment by gir489** [comment]
Revert the unnecessary whitespace changes.

**Comment by papstuc** [comment]
> Revert the unnecessary whitespace changes.
Fixed it

**Comment by gir489** [comment]
This seems like a hack fix. You just added a new option to cover the edge case. Fix the bug properly please.

**Comment by gir489** [comment]
Don't worry about it, I fixed it.

**Pull request closed without merging**
