### PR TITLE
Option for double '??' wildcards

### PR DESCRIPTION
**Pull request by Caraxi**

### CODE REVIEW

**Comment by gir489** [comment]
This commit makes no sense, why would you choose one or the other. Just have the code lexically parse out with RegEx or something the question marks.

**Comment by Caraxi** [comment]
It was for a very specific purpose, it may not be useful to everyone but I figured I'd PR it anyway

**Comment by Caraxi** [comment]
Any updates?

**Comment by gir489** [comment]
Since you're persistent and can't take a hint, my vote was to not merge this if that wasn't abundantly clear. If you want @ajkhoury's vote I'd wager to guess he would say the same, but I can't speak for him since I am not him. Your 2 second fix of a legacy issue isn't unprecedented enough to stop what we're doing in real, quit panicking from the fucking Ukrainian war, and suck your dick. Fuck you.

**Comment by ajkhoury** [comment]
This is implemented poorly imo, but I definitely like the idea of adding support for double wildcards.

**Comment by Caraxi** [comment]
out of curiosity, what is poor about it? I've never written c++ before so I just copied the existing settings that you wrote

**Comment by Caraxi** [comment]
also
fuck you too @gir489
image

**Comment by ajkhoury** [comment]
Double '??' wildcards are for denoting nibble wildcards. A proper implementation should support single nibble wildcards as well e.g. `48 8? C6 ?8`. The way you implemented this is just to accept double '??' wildcards as a single '?'. I can give you a reference implementation of what I mean if you want to integrate it into this project.

**Comment by Caraxi** [comment]
Fair enough I guess. my use case doesn't support nibble wildcards so it's not a big deal to me, I'll just keep my fork

**Pull request closed without merging**
